### ISSUE TITLE
Usar httpStatus

### ISSUE THREAD

**Issue by raupp** [Mathsphysis/API-CRUD-DevOZ#1]
https://github.com/Mathsphysis/API-CRUD-DevOZ/blob/ebbf969c40643151ed597dfb8e434558602b7c1f/src/controller/controllers.js#L32

Poderia usar uma biblioteca para evitar "numeros magicos"

**Comment by Mathsphysis** [comment]
É possível realizar as correções? Eu tenho uma mini biblioteca com os códigos http suportados, mas acabei esquecendo de substituir no controller. Tem alguns outros "numeros magicos" pelo código  também, não me liguei na hora de fazer a refatoração pré-release...

**Comment by Mathsphysis** [comment]
Feita a alteração para retirar números mágicos da base de código.
